services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      - POSTGRES_DB=web3
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=061200
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    container_name: backend
    image: tuananh06/backend:4.0
    env_file:
      - .env
    ports:
      - "3333:3333"
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    image: tuananh06/frontend:6.0
    env_file:
      - .env.production
    ports:
      - "5173:5173"
    depends_on:
      - backend

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend

volumes:
  postgres-data:
